<header class="intro-header" style="background-image: url('<?php echo $this->basePath('img/post-bg.jpg') ; ?>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1><?php echo $blog->title ; ?></h1>
                    <h2 class="subheading"><?php echo $blog->slug ; ?></h2>
                    <span class="meta">Posted by
                        <a href="#"><?php echo $blog->user->firstName . ' ' . $blog->user->lastName ; ?>
                        </a> on <?php echo $blog->createdAt->format('F j,Y') ; ?></span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <?php echo $blog->content ; ?>
            </div>
        </div>
    </div>
</article>

<hr>
