<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new bibo user';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('bi-bo-user', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('email_address'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('first_name'));
echo $this->formRow($form->get('last_name'));
echo $this->formRow($form->get('deleted_flag'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();