<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<?php echo $this->basePath('/img/home-bg.jpg') ; ?>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <hr class="small">
                    <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<?php
$paging = $this->paginationHelper($comments, $page, $this->url('bi-bo-comment', array('action' => 'index')), 10);
foreach ($comments as $comment) : ; ?>
    <div class="post-preview">
        <a href="post.html">
            <h2 class="post-title">
                <?php echo $comment->content; ?>
            </h2>
            <h3 class="post-subtitle">
                <?php echo $comment->blog->title; ?>
            </h3>
        </a>
    </div>
<hr>

<?php endforeach; ?>


<div class="paging">
    <?php echo $paging; ?>
</div>


</div>
        </div>
    </div>

