<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BiBoUser\Module'                        => __DIR__ . '/Module.php',
    'BiBoUser\Controller\SkeletonController' => __DIR__ . '/src/BiBoUser/Controller/BiBoUserController.php',
    'ZendSkeletonModuleTest\Framework\TestCase'        => __DIR__ . '/tests/BiBoUser/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'                => __DIR__ . '/tests/BiBoUser/SampleTest.php',
);