<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new bibo blog';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('bi-bo-blog', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('slug'));
echo $this->formRow($form->get('content'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();